---
version: '3.4'
services:
  benchmark-ann-0:
    build: 
      context: ./
      dockerfile: Dockerfile-ann-0
    volumes:
      - $PWD/benchmark-data:/var/hdf5
      - $PWD/results-0:/var/lib/benchmark/results
  weaviate-0:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '11550'
    - --scheme
    - http
    image: docker.io/semitechnologies/weaviate:1.13.2
    ports:
      - 11550:11550
    volumes:
      - $PWD/weaviate-data-0:/var/lib/weaviate
    restart: on-failure:0
    environment:
      GOGC: 800
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      ENABLE_MODULES: ''
      CLUSTER_HOSTNAME: 'benchmark_node'
...
